### ISSUE TITLE
Text Select Crashes

### ISSUE THREAD

**Issue by JonathonMisiewicz** [CCQC/cheMVP#5]
Under some conditions which I have not yet been able to reproduce successfully, cheMVP will crash. All the crash instances have in common that I have the characters in a text object selected and then try to click elsewhere. Initial testing has shown this is not sufficient to produce the bug.

**Comment by JonathonMisiewicz** [comment]
Now with more detailed reproduction instructions:
Open a document. The one I use is below. Create a text object, type a character, and hit Ctrl/Command + A to select all. Click the button to create another text object, and then select an empty part of the canvas. cheMVP crashes.

[pre.chmvp.zip](https://github.com/CCQC/cheMVP/files/1750530/pre.chmvp.zip)

**Comment by jevandezande** [comment]
My first hack at the problem indicates that `QComboBox::setEditText(QString const&)` is causing the problem in mainwindow_toolbar.cpp on lines 224-228 and 238-242. This code is used for setting the font and other properties of the selected text. When all the selected text elements have the same value for a property, it would display the proper for them, else it would leave the property box blank. It sees that someone neglected to consider the possibility of a property not existing.
I created a pull request for the problem (#8). Check to see if it works for you, and if it does, go ahead and merge the pull request.
